build:
  nodes:
    coverage:
      environment:
        php: 8.0
      dependencies:
        before:
          - sudo apt-get install -y ca-certificates
      tests:
        override:
          - command: ./vendor/bin/phpunit --coverage-clover coverage.xml
            coverage:
              file: coverage.xml
              format: clover