build:
  nodes:
    coverage:
      dependencies:
        before:
          - apt-get install ca-certificates
      tests:
        override:
          - command: ./vendor/bin/phpunit --coverage-clover coverage.xml
            coverage:
              file: coverage.xml
              format: clover